add history

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -109,6 +109,13 @@ jobs:
         with:
           python-version: "3.10"
 
+      - name: Validate browser type
+        run: |
+          if [[ "${{ matrix.BROWSER }}" != "${{ github.event.inputs.browser_type }}" ]]; then
+          echo "Invalid browser type selected: ${{ github.event.inputs.browser_type }} for ${{ matrix.BROWSER }}"
+          exit 1
+          fi
+
       - name: Install browser
         run: |
           if [[ "${{ matrix.BROWSER }}" == "chrome" && "${{ github.event.inputs.browser_type }}" == "Chrome" ]]; then
